### ISSUE TITLE
AddFlog feedback

### ISSUE THREAD

**Issue by alvarix** [alvarix/FLogger#100]
add label 'add title' to input (file ext instructions)
on Submit add flog button, open flog and focus AddEntry
openFlogs immediately updated with new flog

**Comment by alvarix** [comment]
There’s a search bar at top that you type into - if it matches an existing file (potentially with auto complete) then it opens that file for editing. Else it creates a new file.
wdyt?

**Comment by chadcrume** [comment]
No more "add new flog", form visible by default

Placeholder text: "search or create new flog"

No "add flog" button. Select auto-complete option to open flog, or hit return to open flog with exact text match, or hit return to create new flog with text

**Comment by chadcrume** [comment]
How to do the autocomplete dropdown in CSS:
Wrap input and dropdown in a relative element, make the dropdown absolute, and offset it by height of input.
