### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by alvarix** [alvarix/FLogger#26]
1. Properly integrate Tailwind?
2. [Pug](https://pugjs.org/language/tags.html)?

**Comment by chadcrume** [comment]
Tailwind: https://v2.tailwindcss.com/docs/guides/vue-3-vite

**Comment by chadcrume** [comment]
@alvarix , I noticed we have this message in the browser console:

> cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
