### ISSUE TITLE
Text files DB

### ISSUE THREAD

**Issue by alvarix** [alvarix/FLogger#3]

**Comment by chadcrume** [comment]
Looking into the standard Web API called [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API)

**Comment by alvarix** [comment]
@chadcrume FYI id live on in depth breakdown of how you achieve (if you don’t mind )

**Comment by alvarix** [comment]
Looking at FS API
Interesting bcs I think this would mimic the traditional open file, save file interface we get when using our desktop, as opposed to what we would expect from an app. 

Im not necessarily opposed. WDYT?
