### ISSUE TITLE
Classes for Flogger data model

### ISSUE THREAD

**Issue by alvarix** [alvarix/FLogger#35]
- Data model module file. In a "modules" folder parallel with "components"
- Note class with props we've discussed. 
- Later we'll add a Tag class, but not necessary now
- Update AddNote and Note components to use the Note class

Reference https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
Keep it simple with the properties of the class as [Public class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields), and a constructor. You don't need to worry about getters, setters, or private properties. Something as simple as this example from that page:

```
class Person {
  name;
  age;
  constructor(name, age) {
    this.name = name;
    this.age = age;
  }
}
```

**Comment by chadcrume** [comment]
Reference https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
Keep it simple with the properties of the class as [Public class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields), and a constructor. You don't need to worry about getters, setters, or private properties. Something as simple as this example from that page:

```
class Person {
  name;
  age;
  constructor(name, age) {
    this.name = name;
    this.age = age;
  }
}
```

**Comment by alvarix** [comment]
@chadcrume do you mean Models/ instead of Modules/?

**Comment by alvarix** [comment]
@chadcrume finally getting started. 
I didnt seem to write your advices on my computer (maybe on paper).

After I've imported the class what do I have to change in the component so it uses the class?

Also, interestingly it wouldnt resolve the path to the module unless I added the _.vue_ into the filename.
I wonder if the class should just be a _.js_ file? 

LMK if you want me to push.

**Comment by chadcrume** [comment]
Yeah, should be .js file.
You declare a component prop with the class name. So rather than:
node: { message: string, timestamp: Date, tags: Array }
...(or whatever it is now) you do it instead like this;
node: Node

**Comment by alvarix** [comment]
@chadcrume I just pushed up note.vue with the changes. 
It broke the timestamp. 
I was trying to carry thru the model to the rest of the components, but into quite a tangle. 

I figured I have to update AddNote as well, and how the data flows thru App. 
Any pointers here will be helpful, but maybe I just need to unscrew and rescrew on my head to try to make sense.

**Comment by alvarix** [comment]
@chadcrume resolving errors.
I'm getting this:
`[plugin:vite:import-analysis] Failed to resolve import "@vueuse/core" from "src/modules/useDataFile.js". Does the file exist?`

Did you forget to commit something?
I also got errors about pinia, and removed the lines invoking it in main.js

**Comment by alvarix** [comment]
@chadcrume disregard. I npm installed
