### ISSUE TITLE
Convert NoteData constructor param to object 

### ISSUE THREAD

**Issue by alvarix** [alvarix/FLogger#51]
And or TypeScript to set default values, ie. timestamp

**Comment by alvarix** [comment]
Chat's notes from past ticket:
#One option for allowing the "new NoteData" to have named parameters rather than just having to know the correct order:

The constructor takes in an object with named properties, like this:
`constructor({ date, tags, entry }) `
Then new NoteData passes in an object with named properties, like this:
`let x = new NoteData({ date: new Date(), tags: ["tag"], entry: "entry text" }) `

See https://stackoverflow.com/questions/45507428/typescript-create-class-via-constructor-passing-in-named-parameters

**Comment by chadcrume** [comment]
This will be done in https://github.com/alvarix/FLogger/issues/58
