### ISSUE TITLE
Return URL from dbx + isomorphic fetch API + CORS issue

### ISSUE THREAD

**Issue by alvarix** [alvarix/FLogger#98]

**Comment by chadcrume** [comment]
Create new branch and implement fix that's on **_bug/localhost-return-from-dropbox_**

**Comment by chadcrume** [comment]
Taking notes here to record results of different fetch solutions.

## [1dbfdb8](https://github.com/alvarix/FLogger/pull/87/commits/1dbfdb8e7128584f816d621913c587d65b2628d9) uses "isomorphic-fetch" and an arrow function wrapper to keep the reference to the fetch library.

### Distinguishing code

```
import * as fetch from "isomorphic-fetch";
...
    const config = {
        fetch: (...args) => { return fetch(...args) },
...

```

### Log results:

fetch Module {Symbol(Symbol.toStringTag): 'Module', default: ƒ}
globalThis.fetch ƒ fetch() { [native code] }
...
step 1
Uncaught TypeError: As is not a function

**Comment by chadcrume** [comment]
## [ac9d448](https://github.com/alvarix/FLogger/pull/87/commits/ac9d448660bdf087c5e22765046627442fc326a0) uses "cross-fetch" and an arrow function wrapper to keep the reference to the fetch library.

### Preview URL

https://flogger-7sdv4399s-alvarixs-projects.vercel.app/

### Distinguishing code

```
import fetch from "cross-fetch";
...
    const config = {
        fetch: (...args) => { return fetch(...args) },
...

```

### Results: This one worked!

I thought it was failing when I worked on it last week. To be tested more...
